server:
  port: 8088

spring:
  application:
    name: config-server
  profiles:
    active: native

#cloud:
#  config:
#    server:
#      git:
#        uri: https://github.com/Hardik-Kumar1101/microservices-config-server/tree/main
#        clone-on-start: true